# =============================================
# TransmiApp - Backend Configuration
# =============================================

server.port=8080
spring.application.name=transmiapp-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5433}/${DB_NAME:transmiapp_db}
spring.datasource.username=${DB_USER:transmi_user}
spring.datasource.password=${DB_PASSWORD:transmi_pass_2024}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CORS
transmiapp.cors.allowed-origins=${CORS_ORIGINS:http://localhost:4200}

# TransmiApp Custom Config
transmiapp.system.name=TransMilenio
transmiapp.system.city=Bogota
transmiapp.fare.base=2950
transmiapp.fare.currency=COP
